/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg6_jamilvileda;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jamil
 */
public class Principal_Donas extends javax.swing.JFrame {

    /**
     * Creates new form Principal_Donas
     */
    public Principal_Donas() {

        initComponents();
        inv.CargarArchivo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregarproductos = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rb_bebida = new javax.swing.JRadioButton();
        rb_comida = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        tf_precioventa = new javax.swing.JTextField();
        tf_costoproducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_nombreproducto = new javax.swing.JTextField();
        bt_aceptar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jd_listarproductos = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_listarproductos = new javax.swing.JTable();
        bt_listar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jd_bebidas = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_estadobebida = new javax.swing.JTextField();
        tf_tamaño = new javax.swing.JTextField();
        tf_bebida = new javax.swing.JTextField();
        bt_agregarbebida = new javax.swing.JButton();
        jd_comida = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_tipocomida = new javax.swing.JTextField();
        bt_agregarcomida = new javax.swing.JButton();
        bg_tipoalimento = new javax.swing.ButtonGroup();
        jd_facturacion = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_nombrecliente = new javax.swing.JTextField();
        tf_correoelectronico = new javax.swing.JTextField();
        tf_rtn = new javax.swing.JTextField();
        tf_cai = new javax.swing.JTextField();
        tf_fechaactual = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Inventario = new javax.swing.JMenu();
        jmi_agregarproductos = new javax.swing.JMenuItem();
        jmi_listarproductos = new javax.swing.JMenuItem();
        Facturacion = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        RegistrarVentas = new javax.swing.JMenu();
        RegistroVenta = new javax.swing.JMenuItem();
        GuardarInventario = new javax.swing.JMenu();
        Guardarinv = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Productos al Sistema");

        jLabel2.setText("Precio de Venta");

        jLabel3.setText("Precio de Costo");

        bg_tipoalimento.add(rb_bebida);
        rb_bebida.setText("Bebida");

        bg_tipoalimento.add(rb_comida);
        rb_comida.setText("Comida");

        jLabel4.setText("Tipo de producto a ingresar: ");

        tf_precioventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_precioventaActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre de Producto");

        bt_aceptar.setText("Aceptar");
        bt_aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_aceptarMouseClicked(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarproductosLayout = new javax.swing.GroupLayout(jd_agregarproductos.getContentPane());
        jd_agregarproductos.getContentPane().setLayout(jd_agregarproductosLayout);
        jd_agregarproductosLayout.setHorizontalGroup(
            jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarproductosLayout.createSequentialGroup()
                .addGroup(jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarproductosLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_agregarproductosLayout.createSequentialGroup()
                                .addComponent(rb_bebida)
                                .addGap(18, 18, 18)
                                .addComponent(rb_comida))
                            .addGroup(jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_precioventa, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_costoproducto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_nombreproducto, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))
                    .addGroup(jd_agregarproductosLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(jd_agregarproductosLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(bt_aceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(111, 111, 111))
        );
        jd_agregarproductosLayout.setVerticalGroup(
            jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarproductosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_precioventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_costoproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_nombreproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rb_bebida)
                    .addComponent(rb_comida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jd_agregarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_aceptar)
                    .addComponent(jButton3))
                .addGap(45, 45, 45))
        );

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setText("Productos Disponibles en el Sistema");

        jt_listarproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Precio Venta"
            }
        ));
        jt_listarproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_listarproductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_listarproductos);

        bt_listar.setText("Listar Productos");
        bt_listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_listarMouseClicked(evt);
            }
        });

        bt_eliminar.setText("Eliminar Productos");
        bt_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_eliminarMouseClicked(evt);
            }
        });

        jButton1.setText("Modificar Producto");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_listarproductosLayout = new javax.swing.GroupLayout(jd_listarproductos.getContentPane());
        jd_listarproductos.getContentPane().setLayout(jd_listarproductosLayout);
        jd_listarproductosLayout.setHorizontalGroup(
            jd_listarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarproductosLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jd_listarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listarproductosLayout.createSequentialGroup()
                        .addGroup(jd_listarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_listarproductosLayout.createSequentialGroup()
                                .addComponent(bt_listar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_eliminar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listarproductosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(144, 144, 144))))
        );
        jd_listarproductosLayout.setVerticalGroup(
            jd_listarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarproductosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_listarproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_listar)
                    .addComponent(bt_eliminar)
                    .addComponent(jButton1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setText("Ingrese los datos de la bebida a agregar");

        jLabel8.setText("Estado de bebida: ");

        jLabel9.setText("Tamaño:");

        jLabel10.setText("Tipo de Bebida: ");

        bt_agregarbebida.setText("Agregar Bebida");
        bt_agregarbebida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarbebidaMouseClicked(evt);
            }
        });
        bt_agregarbebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregarbebidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_bebidasLayout = new javax.swing.GroupLayout(jd_bebidas.getContentPane());
        jd_bebidas.getContentPane().setLayout(jd_bebidasLayout);
        jd_bebidasLayout.setHorizontalGroup(
            jd_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_bebidasLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(44, 44, 44))
            .addGroup(jd_bebidasLayout.createSequentialGroup()
                .addGroup(jd_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_bebidasLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jd_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(36, 36, 36)
                        .addGroup(jd_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_bebida, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_estadobebida, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_bebidasLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(bt_agregarbebida)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_bebidasLayout.setVerticalGroup(
            jd_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_bebidasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addGap(37, 37, 37)
                .addGroup(jd_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_estadobebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jd_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jd_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_bebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(bt_agregarbebida)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setText("Comida ");

        jLabel12.setText("Tipo de comida: ");

        tf_tipocomida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tipocomidaActionPerformed(evt);
            }
        });

        bt_agregarcomida.setText("Agregar Comida");
        bt_agregarcomida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarcomidaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_comidaLayout = new javax.swing.GroupLayout(jd_comida.getContentPane());
        jd_comida.getContentPane().setLayout(jd_comidaLayout);
        jd_comidaLayout.setHorizontalGroup(
            jd_comidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_comidaLayout.createSequentialGroup()
                .addGroup(jd_comidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_comidaLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel12)
                        .addGap(30, 30, 30)
                        .addComponent(tf_tipocomida, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_comidaLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel11))
                    .addGroup(jd_comidaLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(bt_agregarcomida)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jd_comidaLayout.setVerticalGroup(
            jd_comidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_comidaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel11)
                .addGap(27, 27, 27)
                .addGroup(jd_comidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_tipocomida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(bt_agregarcomida)
                .addGap(14, 14, 14))
        );

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel13.setText("Facturacion");

        jLabel14.setText("Correo Electronico: ");

        jLabel15.setText("Nombre del Cliente:");

        jLabel16.setText("RTN");

        jLabel17.setText("CAI");

        jLabel18.setText("Fecha Actual");

        tf_rtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_rtnActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar Factura");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_facturacionLayout = new javax.swing.GroupLayout(jd_facturacion.getContentPane());
        jd_facturacion.getContentPane().setLayout(jd_facturacionLayout);
        jd_facturacionLayout.setHorizontalGroup(
            jd_facturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_facturacionLayout.createSequentialGroup()
                .addGroup(jd_facturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_facturacionLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel13))
                    .addGroup(jd_facturacionLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jd_facturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jd_facturacionLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jd_facturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_facturacionLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(tf_correoelectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_facturacionLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(28, 28, 28)
                                .addGroup(jd_facturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addGroup(jd_facturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_fechaactual, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                        .addComponent(tf_nombrecliente)
                                        .addComponent(tf_rtn)
                                        .addComponent(tf_cai)))))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jd_facturacionLayout.setVerticalGroup(
            jd_facturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_facturacionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addGap(32, 32, 32)
                .addGroup(jd_facturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(tf_correoelectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jd_facturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_nombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jd_facturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_rtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jd_facturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_cai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jd_facturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_fechaactual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton2)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/pkg6_jamilvileda/donas.png"))); // NOI18N
        jLabel19.setText("jLabel19");

        Inventario.setText("Inventario");

        jmi_agregarproductos.setText("Agregar Productos");
        jmi_agregarproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarproductosActionPerformed(evt);
            }
        });
        Inventario.add(jmi_agregarproductos);

        jmi_listarproductos.setText("Listar/Eliminar/Modificar Productos");
        jmi_listarproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_listarproductosActionPerformed(evt);
            }
        });
        Inventario.add(jmi_listarproductos);

        jMenuBar1.add(Inventario);

        Facturacion.setText("Facturacion");
        Facturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacturacionMouseClicked(evt);
            }
        });
        Facturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturacionActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Imprimir Facturacion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Facturacion.add(jMenuItem1);

        jMenuBar1.add(Facturacion);

        RegistrarVentas.setText("Registrar Ventas");

        RegistroVenta.setText("Registrar Venta");
        RegistroVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroVentaActionPerformed(evt);
            }
        });
        RegistrarVentas.add(RegistroVenta);

        jMenuBar1.add(RegistrarVentas);

        GuardarInventario.setText("Guardar Inventario");

        Guardarinv.setText("Guardar Inventario Total");
        GuardarInventario.add(Guardarinv);

        jMenuBar1.add(GuardarInventario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_precioventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_precioventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_precioventaActionPerformed

    private void bt_aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_aceptarMouseClicked
        if (rb_bebida.isSelected()) {
            jd_bebidas.setModal(true);
            jd_bebidas.pack();
            jd_bebidas.setLocationRelativeTo(this);
            jd_bebidas.setVisible(true);

        } else if (rb_comida.isSelected()) {
            jd_comida.setModal(true);
            jd_comida.pack();
            jd_comida.setLocationRelativeTo(this);
            jd_comida.setVisible(true);

        }

    }//GEN-LAST:event_bt_aceptarMouseClicked

    private void jmi_agregarproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarproductosActionPerformed
        jd_agregarproductos.setModal(true);
        jd_agregarproductos.pack();
        jd_agregarproductos.setLocationRelativeTo(this);
        jd_agregarproductos.setVisible(true);


    }//GEN-LAST:event_jmi_agregarproductosActionPerformed

    private void jmi_listarproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_listarproductosActionPerformed

        jd_listarproductos.setModal(true);
        jd_listarproductos.pack();
        jd_listarproductos.setLocationRelativeTo(this);
        jd_listarproductos.setVisible(true);


    }//GEN-LAST:event_jmi_listarproductosActionPerformed

    private void bt_agregarbebidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarbebidaMouseClicked

        double precioventa = Double.parseDouble(tf_precioventa.getText());
        double preciocosto = Double.parseDouble(tf_costoproducto.getText());
        String nombreproducto = tf_nombreproducto.getText();
        String tamañobebida = tf_tamaño.getText();
        String estadobebida = tf_estadobebida.getText();
        String tipobebida = tf_bebida.getText();

        inv.getProducto().add(new Bebidas(estadobebida, tamañobebida, tipobebida, preciocosto, precioventa, nombreproducto));
        f.getProductos().add(new Bebidas(estadobebida, tamañobebida, tipobebida, preciocosto, precioventa, nombreproducto));
        inv.EscribirArchivo();
        JOptionPane.showMessageDialog(jd_comida, "Se ha guardado exitosamente la bebida. ");

    }//GEN-LAST:event_bt_agregarbebidaMouseClicked

    private void tf_tipocomidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tipocomidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tipocomidaActionPerformed

    private void bt_agregarcomidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarcomidaMouseClicked
        double precioventa = Double.parseDouble(tf_precioventa.getText());
        double preciocosto = Double.parseDouble(tf_costoproducto.getText());
        String tipocomida = tf_tipocomida.getText();
        String nombre = tf_nombreproducto.getText();

        inv.getProducto().add(new Comida(tipocomida, preciocosto, precioventa, nombre));
        f.getProductos().add(new Comida(tipocomida, preciocosto, precioventa, nombre));
        inv.EscribirArchivo();
        JOptionPane.showMessageDialog(jd_comida, "Se ha guardado exitosamente la comida. ");


    }//GEN-LAST:event_bt_agregarcomidaMouseClicked

    private void bt_agregarbebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregarbebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_agregarbebidaActionPerformed

    private void tf_rtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_rtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_rtnActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de Texto", "txt");
        jfc.addChoosableFileFilter(filtro);
        int seleccion = jfc.showSaveDialog(this);
        FileWriter fw = null;
        BufferedWriter bw = null;
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            f = new Factura("./factura.txt", tf_correoelectronico.getText(), tf_nombrecliente.getText(), tf_rtn.getText(), tf_cai.getText(), tf_fechaactual.getText());
            f.EscribirArchivo(f);
            JOptionPane.showMessageDialog(this, "La factura se ha guardado correctamente");
            this.jd_facturacion.dispose();
        }


    }//GEN-LAST:event_jButton2MouseClicked

    private void FacturacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FacturacionMouseClicked

    private void FacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturacionActionPerformed

    }//GEN-LAST:event_FacturacionActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        jd_facturacion.setModal(true);
        jd_facturacion.pack();
        jd_facturacion.setLocationRelativeTo(this);
        jd_facturacion.setVisible(true);


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

        this.jd_agregarproductos.dispose();

    }//GEN-LAST:event_jButton3MouseClicked

    private void RegistroVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroVentaActionPerformed

    private void bt_listarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_listarMouseClicked

        DefaultTableModel modelo = (DefaultTableModel) jt_listarproductos.getModel();
        for (int i = 0; i < inv.getProducto().size(); i++) {
            Object[] newrow = {inv.getProducto().get(i).getNombre(), inv.getProducto().get(i).getPrecioventa(),};
            modelo.addRow(newrow);
        }
    }//GEN-LAST:event_bt_listarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked


    }//GEN-LAST:event_jButton1MouseClicked

    private void jt_listarproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_listarproductosMouseClicked

    }//GEN-LAST:event_jt_listarproductosMouseClicked

    private void bt_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminarMouseClicked
        if (jt_listarproductos.getSelectedRow() >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) jt_listarproductos.getModel();
            modelo.removeRow(jt_listarproductos.getSelectedRow());
            jt_listarproductos.setModel(modelo);
    }//GEN-LAST:event_bt_eliminarMouseClicked

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_Donas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_Donas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_Donas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_Donas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_Donas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Facturacion;
    private javax.swing.JMenu GuardarInventario;
    private javax.swing.JMenuItem Guardarinv;
    private javax.swing.JMenu Inventario;
    private javax.swing.JMenu RegistrarVentas;
    private javax.swing.JMenuItem RegistroVenta;
    private javax.swing.ButtonGroup bg_tipoalimento;
    private javax.swing.JButton bt_aceptar;
    private javax.swing.JButton bt_agregarbebida;
    private javax.swing.JButton bt_agregarcomida;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_listar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jd_agregarproductos;
    private javax.swing.JDialog jd_bebidas;
    private javax.swing.JDialog jd_comida;
    private javax.swing.JDialog jd_facturacion;
    private javax.swing.JDialog jd_listarproductos;
    private javax.swing.JMenuItem jmi_agregarproductos;
    private javax.swing.JMenuItem jmi_listarproductos;
    private javax.swing.JTable jt_listarproductos;
    private javax.swing.JRadioButton rb_bebida;
    private javax.swing.JRadioButton rb_comida;
    private javax.swing.JTextField tf_bebida;
    private javax.swing.JTextField tf_cai;
    private javax.swing.JTextField tf_correoelectronico;
    private javax.swing.JTextField tf_costoproducto;
    private javax.swing.JTextField tf_estadobebida;
    private javax.swing.JTextField tf_fechaactual;
    private javax.swing.JTextField tf_nombrecliente;
    private javax.swing.JTextField tf_nombreproducto;
    private javax.swing.JTextField tf_precioventa;
    private javax.swing.JTextField tf_rtn;
    private javax.swing.JTextField tf_tamaño;
    private javax.swing.JTextField tf_tipocomida;
    // End of variables declaration//GEN-END:variables
Inventario inv = new Inventario("./inventario.txt");
    Factura factura = new Factura("./factura.txt");
    Factura f = new Factura();
}
